# Base chain token configurations
tokens:
  USDC:
    address: "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913"
    decimals: 6
    symbol: "USDC"
    is_stablecoin: true
  
  USDT:
    address: "0x50c5725949A6F0c72E6C4a641F24049A917DB0Cb"
    decimals: 6
    symbol: "USDT"
    is_stablecoin: true
  
  DAI:
    address: "0x50c5725949A6F0c72E6C4a641F24049A917DB0Cb"
    decimals: 18
    symbol: "DAI"
    is_stablecoin: true
  
  WETH:
    address: "0x4200000000000000000000000000000000000006"
    decimals: 18
    symbol: "WETH"
    is_stablecoin: false
  
  # Additional tokens
  WMATIC:
    address: "0x4200000000000000000000000000000000000006"
    decimals: 18
    symbol: "WMATIC"
    is_stablecoin: false

# Price feeds (simplified - in production use Chainlink or similar)
price_feeds:
  USDC: 1.0
  USDT: 1.0
  DAI: 1.0
  WETH: 2000.0  # Example price
  WMATIC: 0.8
