# Arbitrum chain token configurations
tokens:
  USDC:
    address: "0xaf88d065e77c8cC2239327C5EDb3A432268e5831"
    decimals: 6
    symbol: "USDC"
    is_stablecoin: true
  
  USDT:
    address: "0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9"
    decimals: 6
    symbol: "USDT"
    is_stablecoin: true
  
  DAI:
    address: "0xDA10009cBd5D07dd0CeCc66161FC93D7c9000da1"
    decimals: 18
    symbol: "DAI"
    is_stablecoin: true
  
  WETH:
    address: "0x82aF49447D8a07e3bd95BD0d56f35241523fBab1"
    decimals: 18
    symbol: "WETH"
    is_stablecoin: false
  
  # Additional tokens
  ARB:
    address: "0x912CE59144191C1204E64559FE8253a0e49E6548"
    decimals: 18
    symbol: "ARB"
    is_stablecoin: false

# Price feeds (simplified - in production use Chainlink or similar)
price_feeds:
  USDC: 1.0
  USDT: 1.0
  DAI: 1.0
  WETH: 2000.0  # Example price
  ARB: 1.2
