[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = false
verbosity = 2

[profile.default.fuzz]
runs = 1000
max_test_rejects = 65536

[profile.default.invariant]
runs = 256
depth = 15
fail_on_revert = false
call_override = false

[profile.ci]
fuzz = { runs = 10000 }
invariant = { runs = 1000, depth = 20 }

[profile.lite]
fuzz = { runs = 10 }
invariant = { runs = 10, depth = 5 }

[rpc_endpoints]
base = "https://base-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
arbitrum = "https://arb-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
base_testnet = "https://base-goerli.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
arbitrum_testnet = "https://arb-goerli.g.alchemy.com/v2/${ALCHEMY_API_KEY}"

[etherscan]
base = { key = "${BASESCAN_API_KEY}", url = "https://api.basescan.org/api" }
arbitrum = { key = "${ARBISCAN_API_KEY}", url = "https://api.arbiscan.io/api" }
base_testnet = { key = "${BASESCAN_API_KEY}", url = "https://api-goerli.basescan.org/api" }
arbitrum_testnet = { key = "${ARBISCAN_API_KEY}", url = "https://api-goerli.arbiscan.io/api" }
